SOFTWARE_VERSION = "v1.0.0"

# ------------- UI --------------

# Window dimensions
WINDOW_WIDTH  = 1024
WINDOW_HEIGHT = 640

# Title
APP_TITLE = "UniReport"

# Font
FONT = "Segoe UI"

# ------------- Processing --------------
INK_CHANNEL_51_9_G    = '51.9 G'
INK_CHANNEL_51_9_R    = '51.9 R'
INK_CHANNEL_33_39_G   = '33.39 G'
INK_CHANNEL_33_39_R   = '33.39 R'
INK_CHANNEL_51_9_LD_G = '51.9 LD G'
INK_CHANNEL_51_9_LD_R = '51.9 LD R'
INK_CHANNELS = [
  INK_CHANNEL_51_9_G, 
  INK_CHANNEL_51_9_R, 
  INK_CHANNEL_33_39_G, 
  INK_CHANNEL_33_39_R, 
  INK_CHANNEL_51_9_LD_G, 
  INK_CHANNEL_51_9_LD_R
]

INPUT_BATCH_ID                    = "batch_id"
INPUT_SENSOR_NUM                  = "sensor_num"
INPUT_WELL_PERFORM_SPEC           = "Well Performance Specification"
INPUT_WELL_PASS_RATE              = "Well Pass Rate"
INPUT_SENSOR_PASS_RATE            = "Sensor Pass Rate"
INPUT_BATCH_UNIFORMITY_PASS_RATE  = "Batch Uniformity Pass Rate"
INPUT_SENSOR_PERFORMANCE_RESULT   = "Sensor Performance Result"
INPUT_BATCH_PERFORMANCE_RESULT    = "Batch Performance Result"
INPUT_SENSOR_UNIFORMITY_RESULT    = "Sensor Uniformity Result"
INPUT_SENSOR_PERFORMANCE          = "Sensor Performance"
INPUT_BATCH_PERFORMANCE           = "Batch Performance"
INPUT_SENSOR_CV                   = "Sensor CV"
INPUT_SENSOR_UNIFORMITY_CV        = "Sensor Uniformity CV"
INPUT_BATCH_UNIFORMITY            = "Batch Uniformity"
INPUT_LOGICAL_OPERATOR            = "Logical Operator"
INPUT_SPECIFICATION_VALUE         = "Specification Value"
INPUT_BATCH_DISPOSITION           = "Batch Disposition"
INPUT_RESULT                      = "Result"
INPUT_COLS = [
  INPUT_BATCH_ID,
  INPUT_SENSOR_NUM,
  INK_CHANNEL_51_9_G + " " + INPUT_WELL_PERFORM_SPEC,
  INK_CHANNEL_51_9_R + " " + INPUT_WELL_PERFORM_SPEC,
  INK_CHANNEL_33_39_G + " " + INPUT_WELL_PERFORM_SPEC,
  INK_CHANNEL_33_39_R + " " + INPUT_WELL_PERFORM_SPEC,
  INK_CHANNEL_51_9_LD_G + " " + INPUT_WELL_PERFORM_SPEC,
  INK_CHANNEL_51_9_LD_R + " " + INPUT_WELL_PERFORM_SPEC,
  INK_CHANNEL_51_9_G + " " + INPUT_WELL_PASS_RATE,
  INK_CHANNEL_51_9_R + " " + INPUT_WELL_PASS_RATE,
  INK_CHANNEL_33_39_G + " " + INPUT_WELL_PASS_RATE,
  INK_CHANNEL_33_39_R + " " + INPUT_WELL_PASS_RATE,
  INK_CHANNEL_51_9_LD_G + " " + INPUT_WELL_PASS_RATE,
  INK_CHANNEL_51_9_LD_R + " " + INPUT_WELL_PASS_RATE,
  INPUT_SENSOR_PERFORMANCE + " " + INPUT_LOGICAL_OPERATOR,
  INPUT_SENSOR_PERFORMANCE + " " + INPUT_SPECIFICATION_VALUE,
  INK_CHANNEL_51_9_G + " " + INPUT_SENSOR_PERFORMANCE_RESULT,
  INK_CHANNEL_51_9_R + " " + INPUT_SENSOR_PERFORMANCE_RESULT,
  INK_CHANNEL_33_39_G + " " + INPUT_SENSOR_PERFORMANCE_RESULT,
  INK_CHANNEL_33_39_R + " " + INPUT_SENSOR_PERFORMANCE_RESULT,
  INK_CHANNEL_51_9_LD_G + " " + INPUT_SENSOR_PERFORMANCE_RESULT,
  INK_CHANNEL_51_9_LD_R + " " + INPUT_SENSOR_PERFORMANCE_RESULT,
  INK_CHANNEL_51_9_G + " " + INPUT_SENSOR_PASS_RATE,
  INK_CHANNEL_51_9_R + " " + INPUT_SENSOR_PASS_RATE,
  INK_CHANNEL_33_39_G + " " + INPUT_SENSOR_PASS_RATE,
  INK_CHANNEL_33_39_R + " " + INPUT_SENSOR_PASS_RATE,
  INK_CHANNEL_51_9_LD_G + " " + INPUT_SENSOR_PASS_RATE,
  INK_CHANNEL_51_9_LD_R + " " + INPUT_SENSOR_PASS_RATE,
  INPUT_BATCH_PERFORMANCE + " " + INPUT_LOGICAL_OPERATOR,
  INPUT_BATCH_PERFORMANCE + " " + INPUT_SPECIFICATION_VALUE,
  INK_CHANNEL_51_9_G + " " + INPUT_BATCH_PERFORMANCE_RESULT,
  INK_CHANNEL_51_9_R + " " + INPUT_BATCH_PERFORMANCE_RESULT,
  INK_CHANNEL_33_39_G + " " + INPUT_BATCH_PERFORMANCE_RESULT,
  INK_CHANNEL_33_39_R + " " + INPUT_BATCH_PERFORMANCE_RESULT,
  INK_CHANNEL_51_9_LD_G + " " + INPUT_BATCH_PERFORMANCE_RESULT,
  INK_CHANNEL_51_9_LD_R + " " + INPUT_BATCH_PERFORMANCE_RESULT,
  INK_CHANNEL_51_9_G + " " + INPUT_SENSOR_CV,
  INK_CHANNEL_51_9_R + " " + INPUT_SENSOR_CV,
  INK_CHANNEL_33_39_G + " " + INPUT_SENSOR_CV,
  INK_CHANNEL_33_39_R + " " + INPUT_SENSOR_CV,
  INK_CHANNEL_51_9_LD_G + " " + INPUT_SENSOR_CV,
  INK_CHANNEL_51_9_LD_R + " " + INPUT_SENSOR_CV,
  INPUT_SENSOR_UNIFORMITY_CV + " " + INPUT_LOGICAL_OPERATOR,
  INPUT_SENSOR_UNIFORMITY_CV + " " + INPUT_SPECIFICATION_VALUE,
  INK_CHANNEL_51_9_G + " " + INPUT_SENSOR_UNIFORMITY_RESULT,
  INK_CHANNEL_51_9_R + " " + INPUT_SENSOR_UNIFORMITY_RESULT,
  INK_CHANNEL_33_39_G + " " + INPUT_SENSOR_UNIFORMITY_RESULT,
  INK_CHANNEL_33_39_R + " " + INPUT_SENSOR_UNIFORMITY_RESULT,
  INK_CHANNEL_51_9_LD_G + " " + INPUT_SENSOR_UNIFORMITY_RESULT,
  INK_CHANNEL_51_9_LD_R + " " + INPUT_SENSOR_UNIFORMITY_RESULT,
  INK_CHANNEL_51_9_G + " " + INPUT_BATCH_UNIFORMITY_PASS_RATE,
  INK_CHANNEL_51_9_R + " " + INPUT_BATCH_UNIFORMITY_PASS_RATE,
  INK_CHANNEL_33_39_G + " " + INPUT_BATCH_UNIFORMITY_PASS_RATE,
  INK_CHANNEL_33_39_R + " " + INPUT_BATCH_UNIFORMITY_PASS_RATE,
  INK_CHANNEL_51_9_LD_G + " " + INPUT_BATCH_UNIFORMITY_PASS_RATE,
  INK_CHANNEL_51_9_LD_R + " " + INPUT_BATCH_UNIFORMITY_PASS_RATE,
  INPUT_BATCH_UNIFORMITY + " " + INPUT_LOGICAL_OPERATOR,
  INPUT_BATCH_UNIFORMITY + " " + INPUT_SPECIFICATION_VALUE,
  INPUT_BATCH_UNIFORMITY + " " + INPUT_RESULT,
  INPUT_BATCH_DISPOSITION
]

IC_TO_ANALYTE = {
  INK_CHANNEL_51_9_G:     "SO2",
  INK_CHANNEL_51_9_R:     "SO2",
  INK_CHANNEL_33_39_G:    "NH3",
  INK_CHANNEL_33_39_R:    "NH3",
  INK_CHANNEL_51_9_LD_G:  "SO2",
  INK_CHANNEL_51_9_LD_R:  "SO2"
}

ANALYTE = "Analyte"
PERFORMANCE = "Performance"
UNIFORMITY = "Uniformity"

# ------------- PDF Report --------------
PDF_NAME                = "pdf_report.docx"
PDF_TITLE               = "ChemQC Lot Report"
PDF_FOOTER              = "CONFIDENTIAL: This document contains proprietary information and is intended for internal use only. Unauthorized disclosure or distribution is prohibited. This report is for Quality Control purposes only. R&D data is excluded."

PAGE_ORIENTATION        = 1  # WD_ORIENT.PORTRAIT
PAGE_WIDTH_INCHES       = 7.5
TOP_MARGIN_INCHES       = 0.75
BOTTOM_MARGIN_INCHES    = 0.75
LEFT_MARGIN_INCHES      = 0.5
RIGHT_MARGIN_INCHES     = 0.5
CELL_VERTICAL_PADDING_TWIPS = 180 # 0.125"

TABLE_GRID = "Table Grid"
NORMAL_TABLE = "Normal Table"

LOT_SUMMARY_INK           = 'Ink'
LOT_SUMMARY_GREEN_CHAN = 'Green Channel (G)'
LOT_SUMMARY_RED_CHAN   = 'Red Channel (R)'
LOT_SUMMARY_COLS          = [LOT_SUMMARY_INK, 
                             LOT_SUMMARY_GREEN_CHAN,
                             LOT_SUMMARY_RED_CHAN]

IC_RESULT_SUM_PARAMETER = 'Parameter'
IC_RESULT_SUM_SPEC      = 'Specification'
IC_RESULT_SUM_VALUE     = 'Value'
IC_RESULT_SUM_RESULT    = 'Result'
IC_RESULT_SUM_BATCH_SPEC= 'Batch Specification'
IC_RESULT_SUM_BATCH_VAL = 'Batch Value'
IC_RESULT_SUM_BATCH_RES = 'Batch Result'
IC_RESULTS_SUMMARY_COLS = [IC_RESULT_SUM_PARAMETER, 
                          IC_RESULT_SUM_SPEC, 
                          IC_RESULT_SUM_VALUE, 
                          IC_RESULT_SUM_RESULT, 
                          IC_RESULT_SUM_BATCH_SPEC, 
                          IC_RESULT_SUM_BATCH_VAL, 
                          IC_RESULT_SUM_BATCH_RES]

# ------------- Misc. --------------
PASS = "PASS"
FAIL = "FAIL"
NA = "N/A"